### ISSUE TITLE
Add gtex eqtls

### ISSUE THREAD

**Issue by cbizon** [NCATS-Gamma/robokop#233] opened 2019-02-20 13:12 UTC
GTEx contains variants that modify expression of particular genes, in particular tissues.

Structuring this in neo4j sucks, but we can at least handle the variant / gene edges.

**Comment by cbizon** [comment] 2019-05-23 19:25
THere are a lot of variants (36M) but we're going to see what happens if we load them all up.

**Comment by PhillipsOwen** [comment] 2019-05-24 12:27
currently finishing up refactoring code to move the conversion of the GTEx variant_id to an HGVS expression to make it available in the smartBag API container.

**Comment by PhillipsOwen** [comment] 2019-05-24 12:28
after that is complete i will insert 1.5m alleles into the graph database located at robokopdev to measure performance. not this test will not include the hyper edge data.

**Comment by PhillipsOwen** [comment] 2019-05-24 16:23
new hgvs column deployed and GTEx builder code refactored to implement. Decided to try 100k alleles first in my development environment. first 90% got cache hits and went into the graph db in ~30 minutes.

Unfortunately after the cache ran out the performance plummeted. it has now spent a total of 2hrs and has loaded only 97%. that is to say that the last ~7k alleles has taken 1.5 hrs to process. 

I expect this will take another .75-1 hours to complete the 100k alleles.

**Comment by PhillipsOwen** [comment] 2019-05-24 16:26
Well right after the previous comment the connection to ensemble timed out. 

requests.exceptions.ConnectionError: HTTPSConnectionPool(host='rest.ensembl.org', port=443): Max retries exceeded with url: /overlap/region/human/1:206260694-207260694?feature=gene (Caused by NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x0000020F2EFEFCF8>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond',))

**Comment by PhillipsOwen** [comment] 2019-06-03 18:37
Corrections to the code base have appeared to have squelched the exception encountered when accessing the ensembl site for information. some 20 million records were inserted before aborting to add new functionality.

in addition, GTEx builder (about to be deprecated and functionality inserted into a crawler) now appears to be handling hyper edge ids properly now.

all code has been pushed to the GTEx_inclusion branch (which also has been merged with master).

**Closed** 2019-06-20 17:42 UTC
