### ISSUE TITLE
Make ranker output_count a parameter

### ISSUE THREAD

**Issue by cbizon** [NCATS-Gamma/robokop#150] opened 2018-09-10 23:42 UTC
Ranker has a hard limit of returning 250 items.  This makes sense for the UI, or even for quick, but ranker is also part of expand.   We probably want to allow more than 250 back from there.

**Comment by patrickkwang** [comment] 2018-09-11 17:50
Duplicate of #81.

**Closed by patrickkwang** 2018-09-11 17:50 UTC
Labels: Ranking, duplicate, enhancement
